Calculator3
mikhailyaskou/CalculatorUI pull request #5
Opened 2017-05-29 12:21 UTC by mikhailyaskou

2017-06-02 22:01 UTC, imironenko reviewed
Давай 
1. отформатируем код, уберем пустые строки, расставим / удалим пробелы
2. сгруппируем методы по логическим блокам, можно использовать #pragma mark 
3. расставим методы по порядку, init, dealloc, action, delegate methods

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.m
> +static NSString *const errorMessageNan = @"ОШИБКА";
Давай сделаем наименование констант в соответствии с код стайлом `<prefix><к чему относятся><имя>`, напр. `YMACalculatorBrainErrorMessageNan`

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.h
> +@interface Calculator : NSObject
Наименование модельку лучше `CalculatorBrain`, `CalculatorModel`, `CalculatorService`

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.m
> +        [_mapOfOperations retain];
Давай `retain` делать непосредственно при присвоение значения `_mapOfOperation = [@{...} retain]`

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.m
> +- (double)getDecemialDisplayValue {
В наименование метода не должно быть префикса get

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.h
> +- (void)equalsTaped;
Правильнее `tapped` и давай уберем suffix `taped`

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/FormatterForCalculator.h
> +@interface FormatterForCalculator : NSObject
не увидел, где используется данный класс ?

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/FormatterSingleton.h
> +@interface FormatterSingleton : NSObject
Где используется данный класс ?

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/CalculatorViewController.m
> +- (void)deleteLastDigit {
нет необходимости выносить данный метод, он используется единожды, давай внесем реализацию в `deleteLastDigitTapped`

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.h
> +- (void)operationTaped:(NSString *)operation;
Давай сделаем более корректное наименование, напр. `setOperation:`, `handleOperation:`.

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.h
> +- (void)digitTaped:(NSString *)digit;
Давай сделаем более корректное наименование, напр. `addDigit:`, `handleDigit:`, чтобы менее прослеживалась логика контроллера

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.h
> +- (NSString*)fromDecemial:(double) operand;
Действительно ли надо `toDecimal:` и `fromDecimal:` делать публичными методы, они используются только в модели ?

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.m
> +- (void)getPrecent {
Давай не будем использовать префикс `get`

2017-06-02 22:01 UTC, imironenko commented on CalculatorUI/Calculator.m
> +- (void)getSquareRoot {
аналогично

2017-06-02 22:53 UTC, mikhailyaskou commented on CalculatorUI/CalculatorViewController.m
> +- (void)deleteLastDigit {
Он используется дважды. (Нажатие на кнопку и свайп);

2017-06-02 23:13 UTC, imironenko requested changes

2017-06-02 23:13 UTC, imironenko commented on CalculatorUI/CalculatorViewController.m
> +
Давай уберем лишние пустые строки

2017-06-02 23:13 UTC, imironenko commented on CalculatorUI/CalculatorViewController.m
> +- (void)setDisplayValue:(NSString *)displayValue {
Давай перенесем методы делегата ниже и добавим #pragma mark - CalculatorDelegate

2017-06-02 23:13 UTC, imironenko commented on CalculatorUI/CalculatorViewController.m
> +- (void)deleteLastDigit {
ок

2017-06-05 20:05 UTC, imironenko approved these changes
👍

2017-06-06 06:17 UTC, merged